### PR TITLE
Docs: Added documentation on how to retrieve keys from AWS KMS.

### PR DESCRIPTION
**Pull request by innovia**
```release-note
Documentation: updated instructions for how to fetch keys from SSM and KMS after vault init.
```

### CODE REVIEW

**Comment by JoshVanL** [comment]
@innovia Thanks for the PR. Can you please add a release note as described here: https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md

/assign @innovia 
/ok-to-test

**Comment by innovia** [comment]
ping

**Comment by innovia** [comment]
ping

**Comment by innovia** [comment]
It's just docs - can we get this done please?

**Comment by simonswine** [comment]
Thank you @innovia for the docs and the pinging

/lgtm
/approve

**Pull request merged**
